tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "bash"
brew "cmake"
brew "coreutils"
brew "fd"
brew "tesseract"
brew "ffmpeg"
brew "fzf"
brew "gcc"
brew "git"
brew "git-lfs"
brew "htop"
brew "python@3.8"
brew "imagemagick"
brew "libav"
brew "macvim"
brew "mas"
brew "node"
brew "pdfgrep"
brew "pstree"
brew "reattach-to-user-namespace"
brew "rename"
brew "screen"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "alfred"
cask "anaconda"
cask "anki"
cask "chromedriver"
cask "cyberduck"
cask "detexify"
cask "dropbox"
cask "font-computer-modern"
cask "gimp"
cask "inkscape"
cask "iterm2"
cask "java8"
cask "mactex"
cask "mathpix-snipping-tool"
cask "nteract"
cask "pycharm"
cask "signal"
cask "skim"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zotero"
mas "Amphetamine", id: 937984704
mas "iMovie", id: 408981434
mas "Magnet", id: 441258766
mas "Microsoft To Do", id: 1274495053
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
