tap "cloudfoundry/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
cask "xquartz"
brew "bash"
brew "cmake"
brew "cookiecutter"
brew "coreutils"
brew "diff-pdf"
brew "fd"
brew "fzf"
brew "gcc"
brew "git"
brew "git-lfs"
brew "graphviz"
brew "htop"
brew "libav"
brew "libusb"
brew "mas"
brew "maven"
brew "node"
brew "pdfgrep"
brew "pstree"
brew "reattach-to-user-namespace"
brew "rename"
brew "screen"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "cloudfoundry/tap/cf-cli"
cask "alfred"
cask "anaconda"
cask "anki"
cask "cyberduck"
cask "dash"
cask "docker"
cask "dropbox"
cask "font-computer-modern"
cask "gimp"
cask "inkscape"
cask "iterm2"
cask "java8"
cask "mactex"
cask "macvim"
cask "mathpix-snipping-tool"
cask "nteract"
cask "pycharm"
cask "skim"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
cask "zotero"
mas "Amphetamine", id: 937984704
mas "Magnet", id: 441258766
mas "The Unarchiver", id: 425424353
mas "WhatsApp", id: 1147396723
mas "Wunderlist", id: 410628904
mas "Xcode", id: 497799835
